import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Bannerimage from "@/assets/BannerImage.png";
import { NavBar } from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <NavBar />

        <div className={`${styles.content}`}>
          <div className={`${styles.banner}`}>
            <Image src={Bannerimage} alt="Banner Image" />
            <div>
              <h1>Test Title</h1>
              <p>Test content about the website</p>
            </div>
          </div>
        </div>

        <p>Hello World!</p>
      </main>
    </>
  );
}
